import type { Metadata } from "next";
import "./layout.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

  export default function TasksLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="en">
        <body className={``}>
          {children}
        </body>
      </html>
    );
  }